CREATE TABLE CLIENTE(
	ID SERIAL PRIMARY KEY,
	LIMITE INTEGER NOT NULL,
	SALDO INTEGER NOT NULL
);

CREATE TABLE TRANSACAO(
	ID SERIAL PRIMARY KEY,
	VALOR INTEGER NOT NULL,
	TIPO INTEGER NOT NULL,
	DESCRICAO VARCHAR(10) NOT NULL,
	REALIZADA_EM TIMESTAMP,
	CLIENTE_ID INTEGER NOT NULL,
	CONSTRAINT FK_CLIENTE_TRANSACAO FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);