CREATE TABLE CLIENTE(
	ID SERIAL PRIMARY KEY,
	LIMITE INTEGER NOT NULL,
	SALDO INTEGER NOT NULL
);

CREATE TABLE TRANSACAO(
	ID SERIAL PRIMARY KEY,
	VALOR INTEGER NOT NULL,
	TIPO VARCHAR(1) NOT NULL,
	DESCRICAO VARCHAR(10) NOT NULL,
	REALIZADA_EM TIMESTAMP,
	CLIENTE_ID INTEGER NOT NULL,
	CONSTRAINT FK_CLIENTE_TRANSACAO FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

INSERT INTO CLIENTE (LIMITE, SALDO) VALUES (100000, 0);
INSERT INTO CLIENTE (LIMITE, SALDO) VALUES (80000, 0);
INSERT INTO CLIENTE (LIMITE, SALDO) VALUES (1000000, 0);
INSERT INTO CLIENTE (LIMITE, SALDO) VALUES (10000000, 0);
INSERT INTO CLIENTE (LIMITE, SALDO) VALUES (500000, 0);